C FORTRAN 77 IMPLEMENTATION OF WIDELY-KNOWN AND LIKED BKKCRYPT ALGORITHM
C COPY AND PASTE FOLLOWING CODE SNIPPET INTO YOUR PROGRAM AND CALL IT AS USUAL
      CHARACTER(LEN=*) FUNCTION BKKCRYPT(X)
      CHARACTER(LEN=*) X
      BKKCRYPT = X
      RETURN
      END