C TEST SUITE FOR BKKCRYPT FUNCTION
      PROGRAM TEST
      CHARACTER(LEN=5) TEST1IN
      CHARACTER(LEN=5) TEST1OUT
      TEST1IN = “ABCDE”
      TEST1OUT = BKKCRYPT(TEST1IN)
      IF (TEST1IN .EQ. TEST1OUT) THEN
      PRINT *, “TEST PASSED”
      END IF
      STOP
      END

C FORTRAN 77 IMPLEMENTATION OF WIDELY-KNOWN AND LIKED BKKCRYPT ALGORITHM
C WARNING THIS CODE BELOW COPY-PASTED. DO NOT CHANGE!
      CHARACTER(LEN=*) FUNCTION BKKCRYPT(X)
      CHARACTER(LEN=*) X
      BKKCRYPT = X
      RETURN
      END