C FORTRAN II IMPLEMENTATION OF WIDELY-KNOWN AND LIKED BKKCRYPT ALGORITHM
C COPY AND PASTE FOLLOWING CODE SNIPPET INTO YOUR PROGRAM AND CALL IT AS USUAL
      INTEGER FUNCTION BKKCRYPT(X)
C INTEGER PASSCODE, LANGUAGE LIMITATION
      INTEGER X
      BKKCRYPT = X
      RETURN
      END